<!-- BASIC WEBSITE SKELETON, PLEASE DON'T CHANGE ITEMS OUTSIDE THE DIV CLASS BODY -->
<!-- DO NOT EDIT THIS FILE DIRECTLY, COPY ITS CONTENTS TO A NEW FILE AND MAKE CHANGES THERE -->
<?php
$dbhost = "sql12.freesqldatabase.com";
 $dbuser = "sql12337112";
 $dbpass = "yacY8zPDxP";
 $db = "sql12337112";
 $conn = new mysqli($dbhost, $dbuser, $dbpass,$db) or die("Connect failed: %s\n". $conn -> error);
 $doctorname = "karen"; 

 $sqlValue = "SELECT * FROM `booking` WHERE `doctotname`='$doctorname'";
 $resultValue = mysqli_query($conn,$sqlValue);
if (mysqli_num_rows($resultValue) >= 1) {
    while($row = $resultValue->fetch_assoc()) {
        $time = $row['time'];
        $day = $row['day'];
        $month = $row['month'];
        $doctorname = $row['doctorname'];
    
}
$value = "Your booking is at " . "$time on " . "$day/$month " . " with $doctorname."; 
} else {
    $value=""; 
}


	$time = $_POST['time'];
	$day = $_POST['day'];
	$month = $_POST['month'];
	$doctorname = $_POST['doctorname'];




if(isset($_POST['delete'])) {
	
	$sql2 = "DELETE FROM `booking` WHERE `patientname`='$patientname'";
	$result2 = mysqli_query($conn,$sql2);
if (mysqli_affected_rows($conn) > 0) {
//Pass
	$message = "Booking deleted"; 
	 }else {
	$message = "no booking existed"; 
//Fail
}
	}




$conn->close();
?>

<!DOCTYPE html>
<html> 
	<script src="https://kit.fontawesome.com/56b24aa4ed.js" crossorigin="anonymous"></script>
	<head>
		<style>
			.container {
  padding: 40px;
  background-color: white;
}
.button {
  background-color: #add8e6;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
.button:hover { 
	
	color: black;
 }

 input[type="value"] {  
                text-align: center; 
            } 
</style>
		<title>Online Medical Centre</title> <!-- This is the title of the site that shows up in the tab feel free to change it -->
		<link rel="stylesheet" href="WebsiteStyling.css"> <!-- The css file -->
		<script src="WebsiteScript.js"></script> <!-- the javascript file -->
		<link rel="icon" type="image/x-icon" href="favicon.ico"/> <!-- icon file -->
	</head>	
	<body>
		<!-- fixed top navigation bar -->
		<header>
			<div class="navigation" id="nav"> 
				<a id="websiteHeading" href="#websiteHeading" onclick="window.location.href='MAIN-LandingPage.htm'"><i class="fas fa-clinic-medical"></i><b> Online Medical Centre</b></a>
				<div class="navbar-right">
					<a href="#home" onclick="window.location.href='MAIN-LandingPage.htm'"><i class="fas fa-home"></i><b> Home</b></a>
					<a href="#about" onclick="window.location.href='MAIN-AboutPage.htm'"><i class="fas fa-info-circle"></i><b> About</b></a>
					<a href="#contact" onclick="window.location.href='MAIN-ContactPage.htm'"><i class="fas fa-envelope"></i><b> Contact</b></a>
					<a href="#login" onclick="window.location.href='MAIN-LoginPage.htm'"><i class="fas fa-user"></i><b> Login</b></a>
				</div>
				
				<!-- change to toggle menu if the window size is too small to fit top navigation bar comfortably -->
				<a href="javascript:void(0);" class="icon" onclick="navbarResize()"> 
					<i class="fa fa-bars"></i>
				</a>
			</div>
		</header>
		<!-- <?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?> --> 
		<!-- content body of website -->
		<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
		<div class="body">
			<section class="contentContainer">
			
				<!-- ADD YOUR CONTENT HERE -->
				<div class="container"> 
				<center><h1>Appointment Timetable</h1></center>
				<br> 
				<center><input size="50" type="value" style="height:200px;"placeholder="No current bookings" name="booking" value="<?php echo $value ?>">
				</center>
				<br> 

				<center>
				
				<br></br>
				<button type="delete" name="delete" class="button">Delete</button> 
				<br> </br>
				<p style="color:red"; name="error"><?php echo $message ?></p> 
			</center>
			</div>
			</section>
		</div>
		</form>
		<!-- fixed footer bar -->
		<div class="footer">
			<div class="etcDetails">
				<a href="MAIN-FAQPage.htm">FAQ</a>
				<a href="MAIN-Terms&ConditionsPage.htm">Terms &amp; Conditions</a>
				<a href="MAIN-PrivacyPage.htm">Privacy</a>
				<a href="MAIN-SecurityPage.htm">Security</a>
			</div>
			
			<p id="copyRight">&copy; 2020 Online Medical Centre - All Rights Reserved.</p>
		</div>
	</body>
</html>